### ISSUE TITLE
Event.for_repo_issues is broken

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-github#107]
While testing the `Event` API I got:

```
Bad response: Yojson.Json_error("Blank input data")
Fatal error: exception (Failure "Bad response: Yojson.Json_error(\"Blank input data\")\n")
```

I'll try to find a repro.

**Comment by dsheets** [comment]
Possibly due to #85.

**Comment by samoht** [comment]
So the issue is that `Repo.for_repo_issues` is broken. `Repo.for_repo` just works (but has annoyingly more events).

**Comment by dsheets** [comment]
The [docs say](https://developer.github.com/v3/activity/events/#list-issue-events-for-a-repository):

> Repository issue events have a different format than other events, as documented in the [Issue Events API](https://developer.github.com/v3/issues/events/).

I clearly wasn't paying attention when I bound this one...
