### ISSUE TITLE
User/contributor feedback before 1.0.0 release

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-github#78]
I would really appreciate it if the users and contributors to this library could review the [master branch](https://github.com/mirage/ocaml-github), especially the 200 lines of [CHANGES](https://github.com/mirage/ocaml-github/blob/master/CHANGES) for 1.0.0, and let me know their opinions of the new features and (many) breaking changes. Silence will be considered assent. I would appreciate any responses before Tuesday 26 May 2015.

The goal with 1.0.0 will be to provide a consistent, useful, API which will remain stable and supported for more than a year of production use. New features will be incorporated into 1.x but breaking changes will be delayed until 2.0 which should not occur before May 2016.

Any comments, suggestions, feature requests, etc are welcome.

@avsm @andrewray @michipili @jonludlam @hammer @technomancy @phi-gamma @mmottl

@samoht @amirmc @laheadle @talex5 @niksu @gasche @jeromemaloberti

If you know of any contributors, users, or interested parties not mentioned in this issue, please feel free to mention them.

Thank you!

**Comment by dsheets** [comment]
One other thing: I've been using #57 to track the changes on the road to 1.0. The only remaining tasks are:

* a complete name, behavior, and organizational consistency check of the module interfaces and the GitHub JSON data type interfaces
* a simple JavaScript test case

I would appreciate it if people report consistency flaws if they see any and I would very much appreciate any JavaScript testing contributions. :stuck_out_tongue_winking_eye:

**Comment by andrewray** [comment]
I have a javascript iocaml notebook testing the gist stuff.  I'll see if I can dig it out tomorrow and update it for the latest api.

**Comment by michipili** [comment]
Great to read this @dsheets!  Hopefully I will take some time on the weekend to give a look at the upcoming version!

**Comment by dsheets** [comment]
After #82 is merged, 1.0.0 will be released.
