### ISSUE TITLE
Support Statistics API

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-github#86]
See https://developer.github.com/v3/repos/statistics/ for @amirmc's project.
- [x] [Get contributors list with additions, deletions, and commit counts](https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts) (#114)
- [x] [Get the last year of commit activity data](https://developer.github.com/v3/repos/statistics/#get-the-last-year-of-commit-activity-data)
- [x] [Get the number of additions and deletions per week](https://developer.github.com/v3/repos/statistics/#get-the-number-of-additions-and-deletions-per-week)
- [x] [Get the weekly commit count for the repository owner and everyone else](https://developer.github.com/v3/repos/statistics/#get-the-weekly-commit-count-for-the-repository-owner-and-everyone-else)
- [x] [Get the number of commits per hour in each day](https://developer.github.com/v3/repos/statistics/#get-the-number-of-commits-per-hour-in-each-day)

**Comment by tmcgilchrist** [comment]
Think I've covered all these endpoints and this can be closed @Aaylor.
