### ISSUE TITLE
ocaml-github should depend on `ssl` or `tls`

### ISSUE THREAD

**Issue by smondet** [mirage/ocaml-github#94]
Right now it forces the openssl implementation:
https://github.com/mirage/ocaml-github/blob/master/opam#L30

**Comment by avsm** [comment]
I'd prefer to force the TLS implementation instead now that it's been more fully tested.

**Comment by yomimono** [comment]
The `ssl` package is currently hosted on sourceforge and is unavailable more frequently than I'd like.  It would be very nice if someone had time to take a run at removing the dependency here.

**Comment by avsm** [comment]
There are two open PRs on this that are currently causing carnage in DataKit since they have the same commit id ;-) #101 and #108. Just fixing the DataKit thing first and then will merge the actual PR.

**Comment by dsheets** [comment]
This was resolved in #101 and will appear in 1.2.
